server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://my-mysql:3306/form_collection_db"
#    url: "jdbc:mysql://localhost:3306/form_collection_db"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs  # ❌ Không cần /api ở đây
  swagger-ui:
    enabled: true
    path: /swagger-ui  # ❌ Không cần /api ở đây
    operations-sorter: method
    doc-expansion: none

jwt:
  signerKey: "UMMJYnWdL7STrWwWaPakmpPQG2fRk/XmfXBhkRv2ZmBG4QtzxNweLKQ5umTXZ/wc"

logging:
  level:
    org.springframework.security: DEBUG

